# Tags Configuration for PI Data Generator
# Crude Oil Separation Train Process Tags

process_instruments = {
    'TT-101': {'desc': 'Crude Inlet Temperature', 'range': (180, 220), 'units': 'deg F', 'noise': 2.5, 'critical': True},
    'PT-101': {'desc': 'Crude Inlet Pressure', 'range': (85, 115), 'units': 'psig', 'noise': 1.2, 'critical': True},
    'LT-101': {'desc': 'V-101 Separator Level', 'range': (45, 75), 'units': '%', 'noise': 2.8, 'critical': True},
    'LC-101': {'desc': 'V-101 Level Controller Output', 'range': (0, 100), 'units': '%', 'noise': 0.5, 'critical': False},
    'FT-101': {'desc': 'Crude Feed Flow', 'range': (450, 600), 'units': 'gpm', 'noise': 12.0, 'critical': True},
    'FC-101': {'desc': 'Crude Feed Flow Controller Output', 'range': (0, 100), 'units': '%', 'noise': 0.8, 'critical': False},
    'TT-102': {'desc': 'Desalter Inlet Temperature', 'range': (280, 320), 'units': 'deg F', 'noise': 3.2, 'critical': True},
    'PT-102': {'desc': 'Desalter Operating Pressure', 'range': (65, 85), 'units': 'psig', 'noise': 1.8, 'critical': True},
    'LT-102': {'desc': 'Desalter Water Level', 'range': (40, 70), 'units': '%', 'noise': 4.1, 'critical': True},
    'LC-102': {'desc': 'Desalter Level Controller Output', 'range': (0, 100), 'units': '%', 'noise': 0.6, 'critical': False},
    'AT-102': {'desc': 'Desalter Salt Content Analyzer', 'range': (2, 8), 'units': 'PTB', 'noise': 0.3, 'critical': True},
    'TT-301A': {'desc': 'Preheater A Inlet Temperature', 'range': (250, 290), 'units': 'deg F', 'noise': 2.8, 'critical': True},
    'TT-301B': {'desc': 'Preheater A Outlet Temperature', 'range': (380, 420), 'units': 'deg F', 'noise': 4.2, 'critical': True},
    'TT-302A': {'desc': 'Preheater B Inlet Temperature', 'range': (380, 420), 'units': 'deg F', 'noise': 4.1, 'critical': True},
    'TT-302B': {'desc': 'Preheater B Outlet Temperature', 'range': (480, 520), 'units': 'deg F', 'noise': 5.5, 'critical': True},
    'TT-303A': {'desc': 'Preheater C Inlet Temperature', 'range': (480, 520), 'units': 'deg F', 'noise': 5.2, 'critical': True},
    'TT-303B': {'desc': 'Preheater C Outlet Temperature', 'range': (580, 620), 'units': 'deg F', 'noise': 6.8, 'critical': True},
    'TT-201': {'desc': 'Column Feed Temperature', 'range': (580, 620), 'units': 'deg F', 'noise': 6.5, 'critical': True, 'trend': 1.02},
    'PT-201': {'desc': 'Column Top Pressure', 'range': (18, 28), 'units': 'psig', 'noise': 0.8, 'critical': True, 'trend': 1.015},
    'PC-201': {'desc': 'Column Pressure Controller Output', 'range': (0, 100), 'units': '%', 'noise': 0.4, 'critical': False},
    'TT-202': {'desc': 'Column Top Temperature', 'range': (285, 315), 'units': 'deg F', 'noise': 3.8, 'critical': True, 'trend': 1.01},
    'TT-203': {'desc': 'Column Bottom Temperature', 'range': (720, 780), 'units': 'deg F', 'noise': 8.2, 'critical': True, 'trend': 1.025},
    'TC-203': {'desc': 'Column Bottom Temp Controller Output', 'range': (0, 100), 'units': '%', 'noise': 0.7, 'critical': False},
    'TT-204': {'desc': 'Column Tray 10 Temperature', 'range': (420, 460), 'units': 'deg F', 'noise': 4.5, 'critical': False},
    'TT-205': {'desc': 'Column Tray 20 Temperature', 'range': (520, 560), 'units': 'deg F', 'noise': 5.2, 'critical': False},
    'TT-206': {'desc': 'Column Tray 30 Temperature', 'range': (620, 660), 'units': 'deg F', 'noise': 6.1, 'critical': False},
    'LT-201': {'desc': 'Reflux Accumulator Level', 'range': (50, 80), 'units': '%', 'noise': 3.2, 'critical': True},
    'LC-201': {'desc': 'Accumulator Level Controller Output', 'range': (0, 100), 'units': '%', 'noise': 0.5, 'critical': False},
    'FT-201': {'desc': 'Reflux Flow', 'range': (180, 250), 'units': 'gpm', 'noise': 8.5, 'critical': True, 'trend': 1.015},
    'FC-201': {'desc': 'Reflux Flow Controller Output', 'range': (0, 100), 'units': '%', 'noise': 0.6, 'critical': False},
    'TT-207': {'desc': 'Reflux Temperature', 'range': (280, 320), 'units': 'deg F', 'noise': 3.5, 'critical': True},
    'LT-203': {'desc': 'Column Bottom Level', 'range': (35, 65), 'units': '%', 'noise': 4.2, 'critical': True},
    'LC-203': {'desc': 'Bottom Level Controller Output', 'range': (0, 100), 'units': '%', 'noise': 0.7, 'critical': False},
    'FT-203': {'desc': 'Reboiler Circulation Flow', 'range': (800, 1200), 'units': 'gpm', 'noise': 25.0, 'critical': True},
    'TT-208': {'desc': 'Reboiler Outlet Temperature', 'range': (740, 800), 'units': 'deg F', 'noise': 9.2, 'critical': True},
    'TT-301': {'desc': 'Naphtha Draw Temperature', 'range': (280, 320), 'units': 'deg F', 'noise': 3.1, 'critical': True},
    'FT-301': {'desc': 'Naphtha Flow', 'range': (120, 180), 'units': 'gpm', 'noise': 6.5, 'critical': True},
    'FC-301': {'desc': 'Naphtha Flow Controller Output', 'range': (0, 100), 'units': '%', 'noise': 0.8, 'critical': False},
    'AT-301': {'desc': 'Naphtha Quality Analyzer (C5-180F)', 'range': (88, 96), 'units': 'vol%', 'noise': 1.2, 'critical': True},
    'TT-302': {'desc': 'Kerosene Draw Temperature', 'range': (380, 430), 'units': 'deg F', 'noise': 4.2, 'critical': True},
    'FT-302': {'desc': 'Kerosene Flow', 'range': (90, 140), 'units': 'gpm', 'noise': 5.8, 'critical': True},
    'FC-302': {'desc': 'Kerosene Flow Controller Output', 'range': (0, 100), 'units': '%', 'noise': 0.9, 'critical': False},
    'AT-302': {'desc': 'Kerosene Flash Point Analyzer', 'range': (140, 160), 'units': 'deg F', 'noise': 2.1, 'critical': True},
    'TT-303': {'desc': 'Gas Oil Draw Temperature', 'range': (520, 570), 'units': 'deg F', 'noise': 5.8, 'critical': True},
    'FT-303': {'desc': 'Gas Oil Flow', 'range': (60, 110), 'units': 'gpm', 'noise': 4.5, 'critical': True},
    'FC-303': {'desc': 'Gas Oil Flow Controller Output', 'range': (0, 100), 'units': '%', 'noise': 1.1, 'critical': False},
    'TT-304': {'desc': 'Heavy Gas Oil Draw Temperature', 'range': (620, 680), 'units': 'deg F', 'noise': 7.2, 'critical': True},
    'FT-304': {'desc': 'Heavy Gas Oil Flow', 'range': (40, 80), 'units': 'gpm', 'noise': 3.8, 'critical': True},
    'AT-201': {'desc': 'Overhead Gas Analyzer (C1-C4)', 'range': (85, 95), 'units': 'mol%', 'noise': 1.8, 'critical': True, 'trend': 0.985},
    'FT-205': {'desc': 'Overhead Gas Flow', 'range': (15, 35), 'units': 'MMSCFD', 'noise': 2.1, 'critical': True},
    'PT-205': {'desc': 'Overhead Gas Pressure', 'range': (22, 32), 'units': 'psig', 'noise': 0.9, 'critical': True},
    'TT-401': {'desc': 'Overhead Condenser Inlet Temperature', 'range': (285, 315), 'units': 'deg F', 'noise': 3.2, 'critical': True},
    'TT-402': {'desc': 'Overhead Condenser Outlet Temperature', 'range': (120, 140), 'units': 'deg F', 'noise': 2.1, 'critical': True},
    'FT-401': {'desc': 'Cooling Water Flow to Condenser', 'range': (2800, 3500), 'units': 'gpm', 'noise': 45.0, 'critical': True},
    'TT-403': {'desc': 'Cooling Water Inlet Temperature', 'range': (78, 95), 'units': 'deg F', 'noise': 1.8, 'critical': False},
    'TT-404': {'desc': 'Cooling Water Outlet Temperature', 'range': (105, 125), 'units': 'deg F', 'noise': 2.5, 'critical': False},
}

equipment_tags = {
    'P-101A_RUN': {'desc': 'Crude Feed Pump A Running Status', 'type': 'digital'},
    'P-101A_AMPS': {'desc': 'Crude Feed Pump A Motor Current', 'range': (180, 220), 'units': 'Amps', 'noise': 3.2},
    'P-101A_VIB': {'desc': 'Crude Feed Pump A Vibration', 'range': (0.8, 4.0), 'units': 'mm/s', 'noise': 0.15, 'trend': 1.03},
    'P-101B_RUN': {'desc': 'Crude Feed Pump B Running Status', 'type': 'digital'},
    'P-101B_AMPS': {'desc': 'Crude Feed Pump B Motor Current', 'range': (180, 220), 'units': 'Amps', 'noise': 3.1},
    'P-101B_VIB': {'desc': 'Crude Feed Pump B Vibration', 'range': (0.8, 4.0), 'units': 'mm/s', 'noise': 0.18, 'trend': 1.025},
    'P-102A_RUN': {'desc': 'Desalted Crude Pump A Running Status', 'type': 'digital'},
    'P-102A_AMPS': {'desc': 'Desalted Crude Pump A Motor Current', 'range': (195, 235), 'units': 'Amps', 'noise': 3.8},
    'P-102B_RUN': {'desc': 'Desalted Crude Pump B Running Status', 'type': 'digital'},
    'P-102B_AMPS': {'desc': 'Desalted Crude Pump B Motor Current', 'range': (195, 235), 'units': 'Amps', 'noise': 3.5},
    'P-103A_RUN': {'desc': 'Reflux Pump A Running Status', 'type': 'digital'},
    'P-103A_AMPS': {'desc': 'Reflux Pump A Motor Current', 'range': (85, 115), 'units': 'Amps', 'noise': 2.1},
    'P-103B_RUN': {'desc': 'Reflux Pump B Running Status', 'type': 'digital'},
    'P-103B_AMPS': {'desc': 'Reflux Pump B Motor Current', 'range': (85, 115), 'units': 'Amps', 'noise': 2.3},
    'CV-101_POS': {'desc': 'V-101 Drain Valve Position', 'range': (0, 100), 'units': '%', 'noise': 0.5, 'related_controller': 'LC-101'},
    'CV-102_POS': {'desc': 'Feed Flow Control Valve Position', 'range': (0, 100), 'units': '%', 'noise': 0.8, 'related_controller': 'FC-101'},
    'CV-201_POS': {'desc': 'Reflux Control Valve Position', 'range': (0, 100), 'units': '%', 'noise': 0.6, 'related_controller': 'FC-201'},
    'CV-202_POS': {'desc': 'Column Pressure Control Valve Position', 'range': (0, 100), 'units': '%', 'noise': 0.4, 'related_controller': 'PC-201'},
}

calculated_tags = {
    'CRUDE_THROUGHPUT': {'desc': 'Total Crude Throughput', 'range': (450, 600), 'units': 'gpm', 'noise': 15.0},
    'COLUMN_REFLUX_RATIO': {'desc': 'Column Reflux Ratio', 'range': (1.2, 2.8), 'units': 'ratio', 'noise': 0.08},
    'COLUMN_FLOODING': {'desc': 'Column Flooding Indicator', 'range': (65, 85), 'units': '%', 'noise': 2.1},
    'ENERGY_EFFICIENCY': {'desc': 'Unit Energy Efficiency', 'range': (78, 88), 'units': '%', 'noise': 1.2},
    'PRODUCT_RECOVERY_NAPHTHA': {'desc': 'Naphtha Recovery Rate', 'range': (92, 98), 'units': '%', 'noise': 0.8},
    'PRODUCT_RECOVERY_KEROSENE': {'desc': 'Kerosene Recovery Rate', 'range': (89, 96), 'units': '%', 'noise': 1.1},
    'DESALTER_EFFICIENCY': {'desc': 'Desalter Salt Removal Efficiency', 'range': (92, 99), 'units': '%', 'noise': 0.9},
    'HEAT_DUTY_REBOILER': {'desc': 'Column Reboiler Heat Duty', 'range': (85, 125), 'units': 'MMBTU/hr', 'noise': 3.8},
    'HEAT_DUTY_PREHEATER': {'desc': 'Preheater Train Heat Duty', 'range': (65, 95), 'units': 'MMBTU/hr', 'noise': 2.9},
}
